// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpjbzcktaykknzlhqzxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwamJ6Y2t0YXlra256bGhxenh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNDQyNDQsImV4cCI6MjA3MDgyMDI0NH0.Ube1AAcgh2sZQMY4UxFv61r4qP4LAkMamG5vE4oyyv4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});